### ISSUE TITLE
compress R objects for faster download

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/scRNA-seq#16]

**Comment by rkhetani** [comment]
This is not as relevant since we are not having them download objects anymore, but here's what I found:
save(seurat_integrated, file="data/seurat_integrated.RData.bz", compress = "bzip2") compresses files the most!  It compressed the integrated object from 3.4 G to 2G. But, it takes a long time to expand!

I don't think there is a very good solution for one data object at a time, the bzip should be good enough if we really need something.
